ISMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required as auth
from django.views.generic.base import RedirectView
from . import views

urlpatterns = patterns(
    '',
    #url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=False), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/', include("django_markdown.urls")),
    url(r'^RiskManagement/', include('RiskManagement.urls', namespace="risk")),
    url(r'^login/$', "django.contrib.auth.views.login", {"template_name": "login.html"}, name="login"),
    url(r'^logout/$', "django.contrib.auth.views.logout_then_login", name="logout"),
)

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

RiskManagement/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required as auth

from . import views
#from .views import CompanyCreate

urlpatterns = patterns(
    '',
    url(r'^$', views.RiskModel.as_view(), name='index'),
    url(r'^stats_json/$', views.stats_json, name='stats_json'),
    # Company
    url(r'^company/$', views.CompanyList.as_view(), name='company_list'),
    url(r'^company/(?P<pk>\d+)$', views.CompanyDetail.as_view(), name='company_detail'),
    url(r'^company/update/(?P<pk>\d+)/$', auth(views.CompanyUpdate.as_view()), name='company_update'),
    url(r'^company/delete/(?P<pk>\d+)/$', auth(views.CompanyDelete.as_view()), name='company_delete'),
    url(r'^company/create/$', auth(views.CompanyCreate.as_view()), name='company_create'),
    url(r'^company/listjson/$', auth(views.CompanyListJson.as_view()), name='company_list_json'),
    # Department
    url(r'^department/$', views.DepartmentList.as_view(), name='department_list'),
    url(r'^department/(?P<pk>\d+)/$', views.DepartmentDetail.as_view(), name='department_detail'),
    url(r'^department/update/(?P<pk>\d+)/$', auth(views.DepartmentUpdate.as_view()), name='department_update'),
    url(r'^department/delete/(?P<pk>\d+)/$', auth(views.DepartmentDelete.as_view()), name='department_delete'),
    url(r'^department/create/$', auth(views.DepartmentCreate.as_view()), name='department_create'),
    url(r'^department/listjson/$', auth(views.DepartmentListJson.as_view()), name='department_list_json'),
    # Duty
    url(r'^duty/$', views.DutyList.as_view(), name='duty_list'),
    url(r'^duty/(?P<pk>\d+)/$', views.DutyDetail.as_view(), name='duty_detail'),
    url(r'^duty/update/(?P<pk>\d+)/$', auth(views.DutyUpdate.as_view()), name='duty_update'),
    url(r'^duty/delete/(?P<pk>\d+)/$', auth(views.DutyDelete.as_view()), name='duty_delete'),
    url(r'^duty/create/$', auth(views.DutyCreate.as_view()), name='duty_create'),
    url(r'^duty/listjson/$', auth(views.DutyListJson.as_view()), name='duty_list_json'),
    # Staff
    url(r'^staff/$', views.StaffList.as_view(), name='staff_list'),
    url(r'^staff/(?P<pk>\d+)/$', views.StaffDetail.as_view(), name='staff_detail'),
    url(r'^staff/update/(?P<pk>\d+)/$', auth(views.StaffUpdate.as_view()), name='staff_update'),
    url(r'^staff/delete/(?P<pk>\d+)/$', auth(views.StaffDelete.as_view()), name='staff_delete'),
    url(r'^staff/create/$', auth(views.StaffCreate.as_view()), name='staff_create'),
    url(r'^staff/listjson/$', auth(views.StaffListJson.as_view()), name='staff_list_json'),
    # Partner
    url(r'^partner/$', views.PartnerList.as_view(), name='partner_list'),
    url(r'^partner/(?P<pk>\d+)/$', views.PartnerDetail.as_view(), name='partner_detail'),
    url(r'^partner/update/(?P<pk>\d+)/$', auth(views.PartnerUpdate.as_view()), name='partner_update'),
    url(r'^partner/delete/(?P<pk>\d+)/$', auth(views.PartnerDelete.as_view()), name='partner_delete'),
    url(r'^partner/create/$', auth(views.PartnerCreate.as_view()), name='partner_create'),
    url(r'^partner/listjson/$', auth(views.PartnerListJson.as_view()), name='partner_list_json'),
    # Asset_valuation
    url(r'^asset_valuation/$', views.Asset_valuationList.as_view(), name='asset_valuation_list'),
    url(r'^asset_valuation/(?P<pk>\d+)/$', views.Asset_valuationDetail.as_view(), name='asset_valuation_detail'),
    url(r'^asset_valuation/update/(?P<pk>\d+)/$', auth(views.Asset_valuationUpdate.as_view()), name='asset_valuation_update'),
    url(r'^asset_valuation/delete/(?P<pk>\d+)/$', auth(views.Asset_valuationDelete.as_view()), name='asset_valuation_delete'),
    url(r'^asset_valuation/create/$', auth(views.Asset_valuationCreate.as_view()), name='asset_valuation_create'),
    url(r'^asset_valuation/listjson/$', auth(views.Asset_valuationListJson.as_view()), name='asset_valuation_list_json'),
    # Asset
    url(r'^asset/$', views.AssetList.as_view(), name='asset_list'),
    url(r'^asset/(?P<pk>\d+)/$', views.AssetDetail.as_view(), name='asset_detail'),
    url(r'^asset/update/(?P<pk>\d+)/$', auth(views.AssetUpdate.as_view()), name='asset_update'),
    url(r'^asset/delete/(?P<pk>\d+)/$', auth(views.AssetDelete.as_view()), name='asset_delete'),
    url(r'^asset/create/$', auth(views.AssetCreate.as_view()), name='asset_create'),
    url(r'^asset/listjson/$', auth(views.AssetListJson.as_view()), name='asset_list_json'),
    # Vulnerability
    url(r'^vul/$', views.VulnerabilityList.as_view(), name='vulnerability_list'),
    url(r'^vul/(?P<pk>\d+)/$', views.VulnerabilityDetail.as_view(), name='vulnerability_detail'),
    url(r'^vul/update/(?P<pk>\d+)/$', auth(views.VulnerabilityUpdate.as_view()), name='vulnerability_update'),
    url(r'^vul/delete/(?P<pk>\d+)/$', auth(views.VulnerabilityDelete.as_view()), name='vulnerability_delete'),
    url(r'^vul/create/$', auth(views.VulnerabilityCreate.as_view()), name='vulnerability_create'),
    url(r'^vul/listjson/$', auth(views.VulnerabilityListJson.as_view()), name='vulnerability_list_json'),
    # Threat
    url(r'^threat/$', views.ThreatList.as_view(), name='threat_list'),
    url(r'^threat/(?P<pk>\d+)/$', views.ThreatDetail.as_view(), name='threat_detail'),
    url(r'^threat/update/(?P<pk>\d+)/$', auth(views.ThreatUpdate.as_view()), name='threat_update'),
    url(r'^threat/delete/(?P<pk>\d+)/$', auth(views.ThreatDelete.as_view()), name='threat_delete'),
    url(r'^threat/create/$', auth(views.ThreatCreate.as_view()), name='threat_create'),
    url(r'^threat/listjson/$', auth(views.ThreatListJson.as_view()), name='threat_list_json'),
    # Mapping
    url(r'^mapping/$', views.MappingList.as_view(), name='mapping_list'),
    url(r'^mapping/(?P<pk>\d+)/$', views.MappingDetail.as_view(), name='mapping_detail'),
    url(r'^mapping/update/(?P<pk>\d+)/$', auth(views.MappingUpdate.as_view()), name='mapping_update'),
    url(r'^mapping/delete/(?P<pk>\d+)/$', auth(views.MappingDelete.as_view()), name='mapping_delete'),
    url(r'^mapping/create/$', auth(views.MappingCreate.as_view()), name='mapping_create'),
    url(r'^mapping/listjson/$', auth(views.MappingListJson.as_view()), name='mapping_list_json'),
    # Vul_analysis
    url(r'^vul_analysis/$', views.Vul_analysisList.as_view(), name='vul_analysis_list'),
    url(r'^vul_analysis/(?P<pk>\d+)/$', views.Vul_analysisDetail.as_view(), name='vul_analysis_detail'),
    url(r'^vul_analysis/update/(?P<pk>\d+)/$', auth(views.Vul_analysisUpdate.as_view()), name='vul_analysis_update'),
    url(r'^vul_analysis/delete/(?P<pk>\d+)/$', auth(views.Vul_analysisDelete.as_view()), name='vul_analysis_delete'),
    url(r'^vul_analysis/create/$', auth(views.Vul_analysisCreate.as_view()), name='vul_analysis_create'),
    url(r'^vul_analysis/listjson/$', auth(views.Vul_analysisListJson.as_view()), name='vul_analysis_list_json'),
    # Risk_analysis
    url(r'^risk_analysis/$', views.Risk_analysisList.as_view(), name='risk_analysis_list'),
    url(r'^risk_analysis/(?P<pk>\d+)/$', views.Risk_analysisDetail.as_view(), name='risk_analysis_detail'),
    url(r'^risk_analysis/update/(?P<pk>\d+)/$', auth(views.Risk_analysisUpdate.as_view()), name='risk_analysis_update'),
    url(r'^risk_analysis/delete/(?P<pk>\d+)/$', auth(views.Risk_analysisDelete.as_view()), name='risk_analysis_delete'),
    url(r'^risk_analysis/create/$', auth(views.Risk_analysisCreate.as_view()), name='risk_analysis_create'),
    url(r'^risk_analysis/listjson/$', auth(views.Risk_analysisListJson.as_view()), name='risk_analysis_list_json'),
    # Risk_control
    url(r'^risk_control/$', views.Risk_controlList.as_view(), name='risk_control_list'),
    url(r'^risk_control/(?P<pk>\d+)/$', views.Risk_controlDetail.as_view(), name='risk_control_detail'),
    url(r'^risk_control/update/(?P<pk>\d+)/$', auth(views.Risk_controlUpdate.as_view()), name='risk_control_update'),
    url(r'^risk_control/delete/(?P<pk>\d+)/$', auth(views.Risk_controlDelete.as_view()), name='risk_control_delete'),
    url(r'^risk_control/create/$', auth(views.Risk_controlCreate.as_view()), name='risk_control_create'),
    url(r'^risk_control/listjson/$', auth(views.Risk_controlListJson.as_view()), name='risk_control_list_json'),
)

RiskManagement/templates/RiskManagement/asset_update.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="fa fa-pencil"></span> 자산 정보 수정 </h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

{% block extrajs %}
{% endblock %}

RiskManagement/templates/RiskManagement/company_create.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="fa fa-plus"></span> 회사 정보 추가</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    //$('#id_record_date').datetimepicker({
    //    pickTime: false
    //});
    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.

    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
    });
});
</script>
{% endblock extrajs%}

RiskManagement/templates/RiskManagement/company_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  <table class="table-condensed">
  {{ form.as_table }}
  </table>
  <input type="submit" value="Add">
</form>
{% endblock %}

RiskManagement/templates/RiskManagement/department_create.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="fa fa-plus"></span> 부서 정보 추가</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    //$('#id_record_date').datetimepicker({
    //    pickTime: false
    //});
    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.

    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
    });
});
</script>
{% endblock extrajs%}

RiskManagement/templates/RiskManagement/department_detail.html
{% extends "base.html" %}

{% block heading %}
    <h3><h3><span class="fa fa-th"></span> 기본정보</h3>
{% endblock %}

{% block content %}
<!--div class="container"-->
<div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="btn-group">
                    <a href="{% url 'risk:department_list'%}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-stack-overflow"></span> 부서 정보</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:department_create' %}">
                    <button type="button" class="btn btn-success">
                    <span class="fa fa-plus"></span> 추가</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:department_update' pk=object.pk %}">
                    <button type="button" class="btn btn-warning">
                    <span class="fa fa-pencil"></span> 수정</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:department_delete' pk=object.pk %}">
                    <button type="button" class="btn btn-danger">
                    <span class="fa fa-minus"></span> 삭제</button>
                    </a>
                </div>
            </div>
        </div>
</div>
<!--/div-->
<div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <b>{{ object.corpinfo }}</b>
                            </h3>
                        </div>
                        <table class="table table-condensed">
                            <tr>
                                <td width=15%><b>부서명</b></td>
                                <td>{{ object.depart }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>주요 업무</b></td>
                                <td>{{ object.desc }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
</div> <!-- end row -->

{##% if object.submitter == user %##}
{##% endif %##}

<p>작성자:{{ object.submitter }}</p>
{% endblock content %}

RiskManagement/templates/RiskManagement/partner_confirm_delete.html
{% extends "base.html" %}

{% block heading %}<h3>
    <span class="fa fa-times"></span>협력회사 정보 삭제 </h3>{% endblock %}

{% block content %}

<div class="form-group">
    <form action="{% url 'risk:partner_delete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <p><b>ID:{{ object.id }} {{ object.corp_name }} ({{ object.biz_reg_no }})</b>를 지우시겠습니까?</p>
        <br>
        <button type="submit" class="btn btn-primary" action="submit">삭제</button>
        <button type="button" class="btn" onclick="location.href=&quot;{% url 'risk:partner_list' %}&quot;;">취소</button>
    </form>
</div>

{% endblock %}

RiskManagement/templates/RiskManagement/partner_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  <table class="table-condensed">
  {{ form.as_table }}
  </table>
  <input type="submit" value="Add">
</form>
{% endblock %}

RiskManagement/templates/RiskManagement/risk_analysis_confirm_delete.html
{% extends "base.html" %}

{% block heading %}<h3>
    <span class="fa fa-times"></span>위험분석 정보 삭제 </h3>{% endblock %}

{% block content %}

<div class="form-group">
    <form action="{% url 'risk:risk_analysis_delete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <p><b>ID:{{ object.id }} {{ object.corp_name }} ({{ object.biz_reg_no }})</b>를 지우시겠습니까?</p>
        <br>
        <button type="submit" class="btn btn-primary" action="submit">삭제</button>
        <button type="button" class="btn" onclick="location.href=&quot;{% url 'risk:risk_analysis_list' %}&quot;;">취소</button>
    </form>
</div>

{% endblock %}

RiskManagement/templates/RiskManagement/risk_analysis_update.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="fa fa-pencil"></span> 위험 분석</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

{% block extrajs %}
{% endblock %}

RiskManagement/templates/RiskManagement/risk_control_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.risk_action_code }}</h2>
<li>위험 처리 방안: {{ object.risk_action}}</li>
<li>상세 내역: {{ object.desc }}</li>
{% endblock content %}

RiskManagement/templates/RiskManagement/staff_confirm_delete.html
{% extends "base.html" %}

{% block heading %}<h3>
    <span class="fa fa-times"></span>임직원 정보 삭제 </h3>{% endblock %}

{% block content %}

<div class="form-group">
    <form action="{% url 'risk:staff_delete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <p><b>ID:{{ object.id }} {{ object.name }} ({{ object.depart }})</b>를 지우시겠습니까?</p>
        <br>
        <button type="submit" class="btn btn-primary" action="submit">삭제</button>
        <button type="button" class="btn" onclick="location.href=&quot;{% url 'risk:staff_list' %}&quot;;">취소</button>
    </form>
</div>

{% endblock %}

RiskManagement/templates/RiskManagement/staff_create.html
{% extends 'base.html' %}

{% block heading %}
    <h3><span class="fa fa-plus"></span> 임직원 정보 추가</h3>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% csrf_token %}
{% crispy form %}

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(function () {
    //$('#id_record_date').datetimepicker({
    //    pickTime: false
    //});
    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.

    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
});
</script>
{% endblock extrajs%}

RiskManagement/templates/RiskManagement/staff_detail.html
{% extends "base.html" %}

{% block heading %}
    <h3><h3><span class="fa fa-th"></span> 기본정보</h3>
{% endblock %}

{% block content %}
<!--div class="container"-->
<div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="btn-group">
                    <a href="{% url 'risk:staff_list'%}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-stack-overflow"></span> 임직원 정보</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:staff_create' %}">
                    <button type="button" class="btn btn-success">
                    <span class="fa fa-plus"></span> 추가</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:staff_update' pk=object.pk %}">
                    <button type="button" class="btn btn-warning">
                    <span class="fa fa-pencil"></span> 수정</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:staff_delete' pk=object.pk %}">
                    <button type="button" class="btn btn-danger">
                    <span class="fa fa-minus"></span> 삭제</button>
                    </a>
                </div>
            </div>
        </div>
</div>
<!--/div-->
<div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <b>{{ object.name}}</b>
                            </h3>
                        </div>
                        <table class="table table-condensed">
                            <tr>
                                <td width=15%><b>부서</b></td>
                                <td>{{ object.depart }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>직무</b></td>
                                <td>{{ object.duty }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>직위/직책</b></td>
                                <td>{{ object.position }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>근무위치</b></td>
                                <td>{{ object.location }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
</div> <!-- end row -->

{##% if object.submitter == user %##}
{##% endif %##}

<p>작성자:{{ object.submitter }}</p>
{% endblock content %}

RiskManagement/templates/RiskManagement/vul_analysis_detail.html
{% extends "base.html" %}

{% block content %}
<!--div class="container"-->
<div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="btn-group">
                    <a href="{% url 'risk:vul_analysis_list'%}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-stack-overflow"></span> 취약점 분석 정보</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:vul_analysis_create' %}">
                    <button type="button" class="btn btn-success">
                    <span class="fa fa-plus"></span> 추가</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:vul_analysis_update' pk=object.pk %}">
                    <button type="button" class="btn btn-warning">
                    <span class="fa fa-pencil"></span> 수정</button>
                    </a>
                </div>
                <div class="btn-group">
                    <a href="{% url 'risk:vul_analysis_delete' pk=object.pk %}">
                    <button type="button" class="btn btn-danger">
                    <span class="fa fa-minus"></span> 삭제</button>
                    </a>
                </div>
            </div>
        </div>
</div>
<!--/div-->
<div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <b>{{ object.asset}}</b>
                            </h3>
                        </div>
                        <table class="table table-hover">
                            <tr>
                                <td width=15%><b>취약점 코드</b></td>
                                <td>{{ object.vul }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>취약점 항목</b></td>
                                <td>{{ object.vul.entry }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>취약점 분류</b></td>
                                <td>{{ object.vul.classification }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>취약점 소분류</b></td>
                                <td>{{ object.vul.subclass }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>취약점 내용</b></td>
                                <td>{{ object.vul.desc }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>자산</b></td>
                                <td>{{ object.asset }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>자산 관리자</b></td>
                                <td>{{ object.asset.staff_name }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>적용 여부</b></td>
                                <td>{{ object.isapplied}}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>분석 결과</b></td>
                                <td>{{ object.vul_score }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>생성 날짜</b></td>
                                <td>{{ object.created }}</td>
                            </tr>
                            <tr>
                                <td width=15%><b>업데이트</b></td>
                                <td>{{ object.updated }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
</div> <!-- end row -->

{##% if object.submitter == user %##}
{##% endif %##}

<p>작성자:{{ object.submitter }}</p>
{% endblock content %}