ISMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required as auth
from django.views.generic.base import RedirectView
from . import views

urlpatterns = patterns(
    '',
    #url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=False), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/', include("django_markdown.urls")),
    url(r'^RiskManagement/', include('RiskManagement.urls', namespace="risk")),
    url(r'^login/$', "django.contrib.auth.views.login", {"template_name": "login.html"}, name="login"),
    url(r'^logout/$', "django.contrib.auth.views.logout_then_login", name="logout"),
)

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

RiskManagement/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required as auth

from . import views
#from .views import CompanyCreate

urlpatterns = patterns(
    '',
    url(r'^$', views.RiskModel.as_view(), name='index'),
    url(r'^stats_json/$', views.stats_json, name='stats_json'),
    # Company
    url(r'^company/$', views.CompanyList.as_view(), name='company_list'),
    url(r'^company/(?P<pk>\d+)$', views.CompanyDetail.as_view(), name='company_detail'),
    url(r'^company/update/(?P<pk>\d+)/$', auth(views.CompanyUpdate.as_view()), name='company_update'),
    url(r'^company/delete/(?P<pk>\d+)/$', auth(views.CompanyDelete.as_view()), name='company_delete'),
    url(r'^company/create/$', auth(views.CompanyCreate.as_view()), name='company_create'),
    url(r'^company/listjson/$', auth(views.CompanyListJson.as_view()), name='company_list_json'),
    # Department
    url(r'^department/$', views.DepartmentList.as_view(), name='department_list'),
    url(r'^department/(?P<pk>\d+)/$', views.DepartmentDetail.as_view(), name='department_detail'),
    url(r'^department/update/(?P<pk>\d+)/$', auth(views.DepartmentUpdate.as_view()), name='department_update'),
    url(r'^department/delete/(?P<pk>\d+)/$', auth(views.DepartmentDelete.as_view()), name='department_delete'),
    url(r'^department/create/$', auth(views.DepartmentCreate.as_view()), name='department_create'),
    url(r'^department/listjson/$', auth(views.DepartmentListJson.as_view()), name='department_list_json'),
    # Duty
    url(r'^duty/$', views.DutyList.as_view(), name='duty_list'),
    url(r'^duty/(?P<pk>\d+)/$', views.DutyDetail.as_view(), name='duty_detail'),
    url(r'^duty/update/(?P<pk>\d+)/$', auth(views.DutyUpdate.as_view()), name='duty_update'),
    url(r'^duty/delete/(?P<pk>\d+)/$', auth(views.DutyDelete.as_view()), name='duty_delete'),
    url(r'^duty/create/$', auth(views.DutyCreate.as_view()), name='duty_create'),
    url(r'^duty/listjson/$', auth(views.DutyListJson.as_view()), name='duty_list_json'),
    # Staff
    url(r'^staff/$', views.StaffList.as_view(), name='staff_list'),
    url(r'^staff/(?P<pk>\d+)/$', views.StaffDetail.as_view(), name='staff_detail'),
    url(r'^staff/update/(?P<pk>\d+)/$', auth(views.StaffUpdate.as_view()), name='staff_update'),
    url(r'^staff/delete/(?P<pk>\d+)/$', auth(views.StaffDelete.as_view()), name='staff_delete'),
    url(r'^staff/create/$', auth(views.StaffCreate.as_view()), name='staff_create'),
    url(r'^staff/listjson/$', auth(views.StaffListJson.as_view()), name='staff_list_json'),
    # Partner
    url(r'^partner/$', views.PartnerList.as_view(), name='partner_list'),
    url(r'^partner/(?P<pk>\d+)/$', views.PartnerDetail.as_view(), name='partner_detail'),
    url(r'^partner/update/(?P<pk>\d+)/$', auth(views.PartnerUpdate.as_view()), name='partner_update'),
    url(r'^partner/delete/(?P<pk>\d+)/$', auth(views.PartnerDelete.as_view()), name='partner_delete'),
    url(r'^partner/create/$', auth(views.PartnerCreate.as_view()), name='partner_create'),
    url(r'^partner/listjson/$', auth(views.PartnerListJson.as_view()), name='partner_list_json'),
    # Asset_valuation
    url(r'^asset_valuation/$', views.Asset_valuationList.as_view(), name='asset_valuation_list'),
    url(r'^asset_valuation/(?P<pk>\d+)/$', views.Asset_valuationDetail.as_view(), name='asset_valuation_detail'),
    url(r'^asset_valuation/update/(?P<pk>\d+)/$', auth(views.Asset_valuationUpdate.as_view()), name='asset_valuation_update'),
    url(r'^asset_valuation/delete/(?P<pk>\d+)/$', auth(views.Asset_valuationDelete.as_view()), name='asset_valuation_delete'),
    url(r'^asset_valuation/create/$', auth(views.Asset_valuationCreate.as_view()), name='asset_valuation_create'),
    url(r'^asset_valuation/listjson/$', auth(views.Asset_valuationListJson.as_view()), name='asset_valuation_list_json'),
    # Asset
    url(r'^asset/$', views.AssetList.as_view(), name='asset_list'),
    url(r'^asset/(?P<pk>\d+)/$', views.AssetDetail.as_view(), name='asset_detail'),
    url(r'^asset/update/(?P<pk>\d+)/$', auth(views.AssetUpdate.as_view()), name='asset_update'),
    url(r'^asset/delete/(?P<pk>\d+)/$', auth(views.AssetDelete.as_view()), name='asset_delete'),
    url(r'^asset/create/$', auth(views.AssetCreate.as_view()), name='asset_create'),
    url(r'^asset/listjson/$', auth(views.AssetListJson.as_view()), name='asset_list_json'),
    # Vulnerability
    url(r'^vul/$', views.VulnerabilityList.as_view(), name='vulnerability_list'),
    url(r'^vul/(?P<pk>\d+)/$', views.VulnerabilityDetail.as_view(), name='vulnerability_detail'),
    url(r'^vul/update/(?P<pk>\d+)/$', auth(views.VulnerabilityUpdate.as_view()), name='vulnerability_update'),
    url(r'^vul/delete/(?P<pk>\d+)/$', auth(views.VulnerabilityDelete.as_view()), name='vulnerability_delete'),
    url(r'^vul/create/$', auth(views.VulnerabilityCreate.as_view()), name='vulnerability_create'),
    url(r'^vul/listjson/$', auth(views.VulnerabilityListJson.as_view()), name='vulnerability_list_json'),
    # Threat
    url(r'^threat/$', views.ThreatList.as_view(), name='threat_list'),
    url(r'^threat/(?P<pk>\d+)/$', views.ThreatDetail.as_view(), name='threat_detail'),
    url(r'^threat/update/(?P<pk>\d+)/$', auth(views.ThreatUpdate.as_view()), name='threat_update'),
    url(r'^threat/delete/(?P<pk>\d+)/$', auth(views.ThreatDelete.as_view()), name='threat_delete'),
    url(r'^threat/create/$', auth(views.ThreatCreate.as_view()), name='threat_create'),
    url(r'^threat/listjson/$', auth(views.ThreatListJson.as_view()), name='threat_list_json'),
    # Mapping
    url(r'^mapping/$', views.MappingList.as_view(), name='mapping_list'),
    url(r'^mapping/(?P<pk>\d+)/$', views.MappingDetail.as_view(), name='mapping_detail'),
    url(r'^mapping/update/(?P<pk>\d+)/$', auth(views.MappingUpdate.as_view()), name='mapping_update'),
    url(r'^mapping/delete/(?P<pk>\d+)/$', auth(views.MappingDelete.as_view()), name='mapping_delete'),
    url(r'^mapping/create/$', auth(views.MappingCreate.as_view()), name='mapping_create'),
    url(r'^mapping/listjson/$', auth(views.MappingListJson.as_view()), name='mapping_list_json'),
    # Vul_analysis
    url(r'^vul_analysis/$', views.Vul_analysisList.as_view(), name='vul_analysis_list'),
    url(r'^vul_analysis/(?P<pk>\d+)/$', views.Vul_analysisDetail.as_view(), name='vul_analysis_detail'),
    url(r'^vul_analysis/update/(?P<pk>\d+)/$', auth(views.Vul_analysisUpdate.as_view()), name='vul_analysis_update'),
    url(r'^vul_analysis/delete/(?P<pk>\d+)/$', auth(views.Vul_analysisDelete.as_view()), name='vul_analysis_delete'),
    url(r'^vul_analysis/create/$', auth(views.Vul_analysisCreate.as_view()), name='vul_analysis_create'),
    url(r'^vul_analysis/listjson/$', auth(views.Vul_analysisListJson.as_view()), name='vul_analysis_list_json'),
    # Risk_analysis
    url(r'^risk_analysis/$', views.Risk_analysisList.as_view(), name='risk_analysis_list'),
    url(r'^risk_analysis/(?P<pk>\d+)/$', views.Risk_analysisDetail.as_view(), name='risk_analysis_detail'),
    url(r'^risk_analysis/update/(?P<pk>\d+)/$', auth(views.Risk_analysisUpdate.as_view()), name='risk_analysis_update'),
    url(r'^risk_analysis/delete/(?P<pk>\d+)/$', auth(views.Risk_analysisDelete.as_view()), name='risk_analysis_delete'),
    url(r'^risk_analysis/create/$', auth(views.Risk_analysisCreate.as_view()), name='risk_analysis_create'),
    url(r'^risk_analysis/listjson/$', auth(views.Risk_analysisListJson.as_view()), name='risk_analysis_list_json'),
    # Risk_control
    url(r'^risk_control/$', views.Risk_controlList.as_view(), name='risk_control_list'),
    url(r'^risk_control/(?P<pk>\d+)/$', views.Risk_controlDetail.as_view(), name='risk_control_detail'),
    url(r'^risk_control/update/(?P<pk>\d+)/$', auth(views.Risk_controlUpdate.as_view()), name='risk_control_update'),
    url(r'^risk_control/delete/(?P<pk>\d+)/$', auth(views.Risk_controlDelete.as_view()), name='risk_control_delete'),
    url(r'^risk_control/create/$', auth(views.Risk_controlCreate.as_view()), name='risk_control_create'),
    url(r'^risk_control/listjson/$', auth(views.Risk_controlListJson.as_view()), name='risk_control_list_json'),
)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>아이시큐어 위험 관리 시스템</title>

    <!-- CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/sticky-footer-navbar.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block extracss %}
    {% endblock %}

    <!-- Add custom CSS here -->
    {% block customcss %}
    	<style>
    		body {padding-bottom: 40px;}
    	</style>
    {% endblock %}

</head>

<body> 
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <a class="navbar-brand" href="/RiskManagement/">&copy; 아이시큐어 위험 관리 시스템</a>
	  <!--a class="navbar-brand" href="/RiskManagement/"><img id="id_logo" src="/static/images/아이시큐어-3.gif" height="35" title="iSecure logo" alt="iSecure logo" /></img><button type="button" class="btn btn-info"><h5>위험 관리 시스템</h5></button></a-->
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'login' %}">Home</a></li>
		{% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
	    <!--li><a id="welcome" class='feedback_link' href="">{{ user.username }}</a></li-->
            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul-->
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-->
</div>
</nav>

{% block rootcontainer %}
<!--div class="container-fluid">
  <div class="row"-->
        <div class="col-sm-3 col-md-2 col-lg-2 sidebar">
	<div class="navbar-default sidebar" role="navigation">
          <ul class="nav nav-sidebar">
	    <li class="active"><a href="/RiskManagement/"><i class="fa fa-dashboard fa-fw"></i>Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'risk:company_list' %}">회사</a></li>
            <li><a href="{% url 'risk:department_list' %}">부서</a></li>
            <li><a href="{% url 'risk:duty_list' %}">주요 직무</a></li>
            <li><a href="{% url 'risk:staff_list' %}">임직원</a></li>
            <li><a href="{% url 'risk:partner_list' %}">협력 회사</a></li>
            <li><a href="{% url 'risk:asset_list' %}">중요 자산</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'risk:vulnerability_list' %}">취약점 목록</a></li>
            <li><a href="{% url 'risk:threat_list' %}">위협 목록</a></li>
            <!--li><a href="{% url 'risk:asset_valuation_list' %}">자산 평가 기준</a></li-->
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'risk:vul_analysis_list' %}">취약점 분석</a></li>
            <li><a href="{% url 'risk:mapping_list' %}">위협 평가</a></li>
            <li><a href="{% url 'risk:risk_analysis_list' %}">위험 분석</a></li>
            <li><a href="{% url 'risk:risk_control_list' %}">위험 관리</a></li>
          </ul>
	</div>
        </div><!--sidebar-->
        {% block breadcrumbs %}
        {% endblock %}
	<div class="col-sm-9 col-md-10 main">
          <div class="page-header">
            {% block heading %}
	    {% endblock %}
          </div>
          {% block content %}
	  {% endblock %}
	</div><!--main-->
  <!--/div><!--/.row-->
</div--><!-- /.container -->
{% endblock %}

<!--FOOTER>
<div id="footer" class="navbar-default">
<div id="footer">
	<nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container-fluid">
                <footer> 
                  <p class="pull-right"><a href="#">Back to top</a></p>
                  <p class="text-muted">
                      &copy; 2015 <a href="http://www.isecurekr.com">iSecure Inc</a>
                      | <a href="#">Blog</a>
                      | <a href="#">About</a>
                      | <a href="mailto:isecure@isecurekr.com">Contact Us</a>
                  </p>
                </footer>
            </div>
	</nav>
</div-->

<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="/static/jquery-2.1.4.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>

{% block extrajs %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h2><a href="{% url 'risk:index' %}">아이시큐어 위험 관리 시스템</a></h2>
<h2>Login</h2>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>

  <input type="submit" value="login" />
  <input type="hidden" name="next" value="/RiskManagement/" />
</form>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extracss %}
<link href="{% static 'bootstrap/css/signin.css' %}" rel="stylesheet">
{% endblock %}

{% block rootcontainer %}
<div class="container">
  <form class="form-signin" name="loginform" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {% if next %}
      <input type="hidden" name="next" value="/RiskManagement" />
    {% endif %}
    <h2 class="form-signin-heading">Please Log In</h2>
    <input type="text" id="username" name="username" class="form-control"
           placeholder="아이디" required autofocus>
    <input type="password" id="password" name="password" class="form-control"
           placeholder="비밀번호" required>
    {##% if login_failed %##}
    {% if form.error %}
      <p class="text-danger">Sorry, that login was invalid.  Please try again.</p>
    {% endif %}
    <input type="submit" name="submit" value="Log In" class="btn btn-lg btn-primary btn-block"/>
    <input type="hidden" name="next" value="/RiskManagement/">
    <br>
    <p class="text-right">
        <a href="{##% url 'password_reset' %##}">Forgot Password?</a>
    </p>
  </form>
</div>
{% endblock %}